### ISSUE TITLE
Tests for App-Gimei-v0.1.1 have started to fail

### ISSUE THREAD

**Issue by andk** [youpong/App-Gimei#1]
The following two reports were generated before and after I installed YOUPONG/Data-Gimei-v0.4.0.tar.gz for that perl:

- before, pass: http://www.cpantesters.org/cpan/report/eb559220-4532-11ed-aad1-25a89cedbcb2
- after, fail: http://www.cpantesters.org/cpan/report/fe63a942-4532-11ed-8191-96a89cedbcb2

**Comment by youpong** [comment]
Thank you for the report.　I have released the supported version.
Try App-Gimei-v0.2.0.
